name: 'C++ CI'

on:
  workflow_dispatch:
    inputs:
        version:
          description: 'Версия релиза (например: v1.0.0)'
          required: true
          type: string
        release_notes:
          description: 'Примечания к релизу'
          required: false
          type: string
          default: 'Релиз создан через GitHub Actions'
jobs:
  build-ubuntu:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v4

      - name: Prepare system
        run: sudo apt-get update -y && sudo apt-get install libboost-test-dev -y
        

      - name: Configure Cmake
        run: |
          cmake -B build -S . -DCMAKE_BUILD_TYPE=Release -DPATCH_VERSION=${{ github.run_number }}

      - name: Build
        run: |
          cmake --build build --config Release --target package

      - name: Upload Release Assets
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: bash
        run: |
          gh release create v2026.0.${{ github.run_number }} \
            build/mp3-player-2026.0.${{ github.run_number }}-Linux.tar.gz \
            build/mp3-player-2026.0.${{ github.run_number }}-Linux.zip

  build-windows:
    needs: build-ubuntu
    runs-on: windows-latest
    permissions: write-all
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Dowload and Configure vcpkg
        run: |
          git clone https://github.com/Microsoft/vcpkg.git
          .\vcpkg\bootstrap-vcpkg.bat
          .\vcpkg\vcpkg install boost-test --triplet x64-windows


      - name: Configure CMake
        run: |
          cmake -B build -S . -G "Visual Studio 17 2022" -A x64 -DCMAKE_TOOLCHAIN_FILE="vcpkg/scripts/buildsystems/vcpkg.cmake" -DPATCH_VERSION=${{ github.run_number }}

      - name: Build
        run: |
          cmake --build build --config Release --target package

      - name: Upload Release Assets
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: cmd
        run: |
          gh release upload v2026.0.${{ github.run_number }} \
            build\mp3-player-2026.0.${{ github.run_number }}-win64.zip \
            build\mp3-player-2026.0.${{ github.run_number }}-win64.tar.gz
