name: 'C++ CI'

on:
  workflow_dispatch:
    inputs:
        version:
          description: 'Версия релиза (например: v1.0.0)'
          required: true
          type: string
        release_notes:
          description: 'Примечания к релизу'
          required: false
          type: string
          default: 'Релиз создан через GitHub Actions'
jobs:
  build-ubuntu:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v4

      - name: Prepare system
        run: sudo apt-get update -y && sudo apt-get install libboost-test-dev -y

      - name: Configure CMake
        run: |
          cmake -B build -S . \
            -DCMAKE_BUILD_TYPE=Release \
            -DPATCH_VERSION=${{ github.run_number }} \
            -DSFML_BUILD_WINDOW=OFF \
            -DSFML_BUILD_GRAPHICS=OFF \
            -DSFML_BUILD_NETWORK=OFF \
            -DSFML_USE_SYSTEM_DEPS=OFF \
            -DCPACK_PACKAGE_FILE_NAME=${{ github.event.inputs.version }}-Linux

      - name: Build
        run: |
          cmake --build build --config Release --parallel 2 --target package

      - name: Upload Linux package artifact
        uses: actions/upload-artifact@v4
        with:
          name: linux-package
          path: build

  release:
    needs: [build-ubuntu]
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v4

      - name: Download Linux package artifact
        uses: actions/download-artifact@v4
        with:
          name: linux-package
          path: build/*.tar.gz
      - name: Publish release
        run: |
          set -e
          if ! gh release create "${{ github.event.inputs.version }}" --notes "${{ github.event.inputs.release_notes }}" build/*.tar.gz; then
            gh release upload "${{ github.event.inputs.version }}" build/*.tar.gz
          fi
